#!/usr/bin/env python3
"""Regenerate or check the public synthetic return-scenario golden fixture."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from return_scenario_engine import (  # noqa: E402
    calculate_scenario,
    display_basis_points,
    display_cents,
    display_hundredths,
    first_anniversary,
    parse_amount_to_cents,
    pearson_correlation,
    round_half_away_from_zero,
)

FIXTURE = ROOT / "fixtures" / "golden-v1.json"


def canonical(payload: object) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n").encode()


def scalar_anchors() -> dict[str, object]:
    return {
        "rounding": {
            "centsPositiveHalf": display_cents(1.005),
            "basisPointsNegativeHalf": display_basis_points(-0.00005),
            "basisPointsPositiveHalf": display_basis_points(0.00005),
            "hundredthsNegativeHalf": display_hundredths(-1.235),
            "hundredthsPositiveHalf": display_hundredths(1.235),
            "directNegativeZero": round_half_away_from_zero(-0.0),
        },
        "dates": {"february29FirstAnniversary": first_anniversary("2024-02-29")},
        "correlation": {
            "identicalNonconstant": pearson_correlation([1, 2, 3], [2, 4, 6]),
            "zeroVariance": pearson_correlation([1, 1, 1], [2, 3, 4]),
        },
    }


def regenerate(template: dict[str, object]) -> dict[str, object]:
    payload = dict(template)
    payload["scenarioCases"] = [
        {
            "id": item["id"],
            "input": item["input"],
            "expected": calculate_scenario(item["input"]),
            **({"tags": item["tags"]} if "tags" in item else {}),
        }
        for item in template["scenarioCases"]
    ]
    payload["parserCases"] = [
        {"input": item["input"], "expected": parse_amount_to_cents(item["input"])}
        for item in template["parserCases"]
    ]
    payload["scalarAnchors"] = scalar_anchors()
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="Write regenerated public fixture bytes.")
    parser.add_argument("--check", action="store_true", help="Fail if committed fixture differs from regenerated bytes.")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("select exactly one of --write or --check")
    existing = json.loads(FIXTURE.read_text())
    generated = canonical(regenerate(existing))
    if args.check:
        if FIXTURE.read_bytes() != generated:
            print("fixture drift: run tools/generate_golden.py --write", file=sys.stderr)
            return 1
        print(f"ok {FIXTURE.relative_to(ROOT)}")
        return 0
    FIXTURE.write_bytes(generated)
    print(f"wrote {FIXTURE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
